[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo ='thinca/vim-singleton'

#[[plugins]]
#repo = 'thinca/vim-quickrun'
#[[plugins]]
#repo = 'vim-scripts/a.vim'
#[[plugins]]
#repo = 'fatih/vim-go'
#call dein#add('justmao945/vim-clang')
#call dein#add('Shougo/vimproc.vim', {'build': 'make'})
#call dein#add('Shougo/neocomplete.vim')
#call dein#add('Shougo/neosnippet.vim')
#call dein#add('Shougo/neosnippet-snippets')
