[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo ='thinca/vim-singleton'

[[plugins]]
repo = 'tomasr/molokai'
